postgres:
    image: postgres
    environment:
        - "POSTGRES_USER=taiga"
        - "POSTGRES_DB=taiga"

taigaback:
    image: dougg/taiga-back
    links:
        - postgres:postgres
    ports:
        - "8000:8000"

taigafront:
    image: dougg/taiga-front
    links:
        - taigaback:taiga-back
    ports:
        - "8080:80"
    environment:
        - "BASE_PROTOCOL=http"
        - "BASE_DOMAIN=ip-address:8000"
